vich_uploader:
    db_driver: orm

    mappings:
        projects_images:
            uri_prefix: /project_img
            upload_destination: "%kernel.project_dir%/public/project_img"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true